// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-olfGz8wTEeEWxbnSdar2nIE8ei7NdaA',
    appId: '1:152988607287:web:b46b33ff5885ae679430b2',
    messagingSenderId: '152988607287',
    projectId: 'my-crapa-project',
    authDomain: 'my-crapa-project.firebaseapp.com',
    storageBucket: 'my-crapa-project.appspot.com',
    measurementId: 'G-5W3HQHWJF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCau5Rzro69slS8FTBA_SH-ulhtEodBhdg',
    appId: '1:152988607287:android:7bcf303a6ace58639430b2',
    messagingSenderId: '152988607287',
    projectId: 'my-crapa-project',
    storageBucket: 'my-crapa-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4g6vfcCt_ja8KMCmAWibuyhL7Nax_J9M',
    appId: '1:152988607287:ios:500d618cc70a82c29430b2',
    messagingSenderId: '152988607287',
    projectId: 'my-crapa-project',
    storageBucket: 'my-crapa-project.appspot.com',
    iosBundleId: 'com.example.futterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4g6vfcCt_ja8KMCmAWibuyhL7Nax_J9M',
    appId: '1:152988607287:ios:965deef94c9eda3f9430b2',
    messagingSenderId: '152988607287',
    projectId: 'my-crapa-project',
    storageBucket: 'my-crapa-project.appspot.com',
    iosBundleId: 'com.example.futterApp.RunnerTests',
  );
}
